.ig
WikiTeX: expansible mod_tex client for MediaWiki
Copyright(C) 2004-7 Peter Danenberg
See doc/COPYING for details.
..
.so header.ms
.RP
.DA
.ds LH TODO
.ds RH WikiTeX @VERSION@
.P1
.TL
WikiTeX @VERSION@ TODO
.AU
Peter Danenberg <pcd at wikitex dot org>
.AI
http://wikisophia.org
.AB
Exigenda and exacta contained herein.
.AE
.XH 1 Exigenda
.IP Tags
Allow specification of alternate (on-the-fly?) tags;
<img src="IMAGE/PNG" />, etc.  Substitution according
to mime.
.XH 1 Exacta
.so footer.ms
